### PR TITLE
Revert "Added lots of files for MSR" they need to be verified Please!

### PR DESCRIPTION
**Pull request by RobinBijo**
Reverts rbkenmiles/XExpo-Projects#2

### CODE REVIEW

**Comment by RobinBijo** [comment]
Especially the patrickmcb one

**Comment by rbkenmiles** [comment]
I think it is fine! No issues with that

**Comment by RobinBijo** [comment]
Ok then do the merging,or I willl do it!

**Comment by RobinBijo** [comment]
It is done! Thank you and we shall see any changes are required! @rbkenmiles

**Comment by rbkenmiles** [comment]
@RobinBijo Cool 😎  I have seen it thanks!

**Comment by rbkenmiles** [comment]
Where are the files?

**Comment by rbkenmiles** [comment]
Is it deleted?

**Pull request merged**
